const initialData = [{"enable_tracking_reminder":"Hi ! Hope you are doing well ! This is a reminder to turn on tracking for XPO load you'll pick up in 2 hours. Say 'Instructions' if you need  help getting tracking enabled."},{"enable_tracking_instructions":"To enable tracking, please tap on the menu icon on the top right of the screen and then tap on the enable tracking menu. If you are still unable to enable tracking please say ,'Enable tracking for me'."},{"enable_tracking_done":"I have enabled tracking for you. Have a safe journey ahead."},
{"conversations":"[{\"sender\":\"bot\",\"message\":\"Hi ! Hope you are doing well ! This is a reminder to turn on tracking for XPO load you'll pick up in 2 hours. Say 'Instructions' if you need  help getting tracking enabled.\"},{\"sender\":\"bot\",\"message\":\"Hi ! Hope you are doing well ! This is a reminder to turn on tracking for XPO load you'll pick up in 2 hours. Say 'Instructions' if you need  help getting tracking enabled.\"},{\"sender\":\"bot\",\"message\":\"Hi ! Hope you are doing well ! This is a reminder to turn on tracking for XPO load you'll pick up in 2 hours. Say 'Instructions' if you need  help getting tracking enabled.\"},{\"sender\":\"driver\",\"message\":\"instructions\"},{\"sender\":\"driver\",\"message\":\"enable tracking for me\"},{\"sender\":\"bot\",\"message\":\"Have you been loaded with correct weight and quantity per the BOL. Say, 'YES', 'NO', 'REPEAT' or you can say 'REPRESENTATIVE' to talk to your rep.\"},{\"sender\":\"driver\",\"message\":\"yes\"},{\"sender\":\"bot\",\"message\":\"We have noted down your response. Thank you\"},{\"sender\":\"driver\",\"message\":\"no\"},{\"sender\":\"bot\",\"message\":\"We have noted down your response. Thank you\"},{\"sender\":\"bot\",\"message\":\"You are scheduled to arrive at 3pm, will you be on time ? Say, 'YES', 'NO', 'REPEAT' or you can say 'REPRESENTATIVE' to talk to your rep.\"},{\"sender\":\"driver\",\"message\":\"yes\"},{\"sender\":\"bot\",\"message\":\"We have noted down your response. Thank you\"},{\"sender\":\"driver\",\"message\":\"no\"},{\"sender\":\"bot\",\"message\":\"We have noted down your response. Thank you\"},{\"sender\":\"bot\",\"message\":\"Did the customer accept the load ? Were there any additinal charges ?\"},{\"sender\":\"driver\",\"message\":\"no\"},{\"sender\":\"bot\",\"message\":\"We have noted down your response. Thank you\"}]"},
{"confirm_load_pickup":"Have you been loaded with correct weight and quantity per the BOL. Say, 'YES', 'NO', 'REPEAT' or you can say 'REPRESENTATIVE' to talk to your rep."},{"confirm_eta":"You are scheduled to arrive at 3pm, will you be on time ? Say, 'YES', 'NO', 'REPEAT' or you can say 'REPRESENTATIVE' to talk to your rep."},{"confirm_delivery":"Did the customer accept the load ? Were there any additinal charges ?"}]

function initData() {
    localStorage.clear();
    initialData.forEach((item)=>{
        for (var key in item) {
            localStorage.setItem(key, item[key]);
        }
    });
}

export default initData;